### ISSUE TITLE
No such file or directory: '.../puma-simulator/test/testasm/large/tile4/tile_imem.npy'

### ISSUE THREAD

**Issue by mhsamavatian** [Aayush-Ankit/dpe_emulate#14]
When running dpe.py

**Comment by mhsamavatian** [comment]
There is no tile4 folder. 
I changed the num_tile_compute = 2 (there is tile0 to tile3 in test folder, 2 for in and out so 2 left right?)
Then this error came out

('Cycle: ', 0, 'Tile halt list', [0, 0, 0, 0])
('Cycle: ', 1, 'Tile halt list', [0, 0, 0, 0])
Traceback (most recent call last):
  File "src/dpe.py", line 168, in <module>
    DPE().run(net)
  File "src/dpe.py", line 122, in run
    node_dut.node_run(cycle)
  ......
/ima.py", line 286, in do_decode
    assert (self.fd_instrn['r1'] >= datamem_off), 'load address for tile memory comes from data memory'
AssertionError: load address for tile memory comes from data memory

**Comment by mhsamavatian** [comment]
The instructions are confusing would you please give clear instructions on how rerun the PUMA benchmarks first? 
and second, how to run modified models in the benchmark folder?

**Comment by mhsamavatian** [comment]
**there are errors and ambiguity in all steps:**
--> compile a model:

**what is the output of the compile? .test files?** 

--> 1- Copy /test/generate-py.sh and /test/input.py files to the /test folder (you only need to do this once).
**Copy from the test folder into the test folder? from the simulator test folder to the compiler test folder? generate.py is in the utils folder. **

2- Edit /test/generate-py.sh file, line 4 and change the value of SIMULATOR_PATH variable.

SIMULATOR_PATH="<emulator_root_path>"
3- Execute the generate-py.sh script
**whats is the input of this script? I ran it without any input, it also needs populate.py. It has several errors, last one is 
def propagate_op_dummy (self, inp1 = 'nil', inp2 = 'nil', lr=1, in1_bit=cfg.dac_res, in2_bit=cfg.xbar_bits):
AttributeError: 'module' object has no attribute 'dac_res' ** 

4- Look at the number of tiles generated by the compiler for ths model and update the value of "num_tile_compute" entry in /include/config.py file to match the number fo compute tiles generated by compiler (remember that Til0 and Tile1 are used for input and output)

--> 5- Go to emulator src directory (/src) and execute dpe.py:

python2 dpe.py -n <model_name>

**This already has problem with the number of tiles from previous comments**
